// wiki_links.mjs: for every code that points at English Wikipedia, the same article in the language, as Wikipedia's
// own language links give it (none are guessed). → i18n/<lang>/wiki.yaml { refId: url }, which stage.mjs uses in place
// of the English url (i18n/<lang>/refs.yaml can still override one). An article with no counterpart keeps the English.
//   node i18n/tools/wiki_links.mjs [--lang=es]
import { writeFileSync } from 'node:fs';
import YAML from 'yaml';
import { readYaml, optYaml, dirOf, langOf, args, langLinks } from './i18n_lib.mjs';

const lang = langOf(args), out = `${dirOf(lang)}/wiki.yaml`;
const refs = [...readYaml('script/refs.yaml'), ...(optYaml('script/notes_refs.yaml', []) || [])];
const wiki = refs.map(r => [r, (r.url || '').match(/^https:\/\/en\.wikipedia\.org\/wiki\/([^#?]+)(#.*)?$/)]).filter(([, m]) => m);
const found = await langLinks(wiki.map(([, m]) => decodeURIComponent(m[1]).replace(/_/g, ' ')), lang);
const map = {}, missing = [];
for (const [r, m] of wiki) { const u = found[decodeURIComponent(m[1]).replace(/_/g, ' ')]; if (u) map[r.id] = u; else missing.push(r.id); }
writeFileSync(out, `# GENERATED by i18n/tools/wiki_links.mjs from Wikipedia's language links (${new Date().toISOString().slice(0, 10)}); do not edit.\n` +
  `# Codes with no ${lang} article keep the English: ${missing.join(', ') || 'none'}\n` + YAML.stringify(map));
console.log(`${out}: ${Object.keys(map).length} of ${wiki.length} Wikipedia codes have a ${lang} article`);
