// wiki_links.mjs: for every code that points at English Wikipedia, the same article in the language, as Wikipedia's
// own language links give it (none are guessed). → i18n/<lang>/wiki.yaml { refId: url }, which stage.mjs uses in place
// of the English url (i18n/<lang>/refs.yaml can still override one). An article with no counterpart keeps the English.
//   node i18n/tools/wiki_links.mjs [--lang=es]
import { writeFileSync } from 'node:fs';
import YAML from 'yaml';
import { readYaml, optYaml, dirOf, langOf, args } from './i18n_lib.mjs';

const lang = langOf(args), out = `${dirOf(lang)}/wiki.yaml`;
const refs = [...readYaml('script/refs.yaml'), ...(optYaml('script/notes_refs.yaml', []) || [])];
const wiki = refs.map(r => [r, (r.url || '').match(/^https:\/\/en\.wikipedia\.org\/wiki\/([^#?]+)(#.*)?$/)]).filter(([, m]) => m);
const titles = [...new Set(wiki.map(([, m]) => decodeURIComponent(m[1]).replace(/_/g, ' ')))];
const found = {};
for (let i = 0; i < titles.length; i += 50) {   // the API takes 50 titles a request
  const q = new URLSearchParams({ action: 'query', format: 'json', prop: 'langlinks', lllang: lang, lllimit: 'max', redirects: '1', titles: titles.slice(i, i + 50).join('|') });
  const j = await (await fetch(`https://en.wikipedia.org/w/api.php?${q}`, { headers: { 'User-Agent': 'axol-f translation tool (https://github.com/curtcox/axol-f)' } })).json();
  const back = {};   // the title each asked-for title ended up as (normalized, redirected)
  for (const n of [...(j.query.normalized || []), ...(j.query.redirects || [])]) back[n.to] = [...(back[n.to] || []), n.from];
  const origins = t => [t, ...(back[t] || []).flatMap(origins)];
  for (const p of Object.values(j.query.pages)) {
    const ll = p.langlinks?.[0]?.['*'];
    if (ll) for (const t of origins(p.title)) found[t] = `https://${lang}.wikipedia.org/wiki/${encodeURIComponent(ll.replace(/ /g, '_')).replace(/%2F/g, '/').replace(/%3A/g, ':').replace(/%2C/g, ',').replace(/%28/g, '(').replace(/%29/g, ')')}`;
  }
}
const map = {}, missing = [];
for (const [r, m] of wiki) { const u = found[decodeURIComponent(m[1]).replace(/_/g, ' ')]; if (u) map[r.id] = u; else missing.push(r.id); }
writeFileSync(out, `# GENERATED by i18n/tools/wiki_links.mjs from Wikipedia's language links (${new Date().toISOString().slice(0, 10)}); do not edit.\n` +
  `# Codes with no ${lang} article keep the English: ${missing.join(', ') || 'none'}\n` + YAML.stringify(map));
console.log(`${out}: ${Object.keys(map).length} of ${wiki.length} Wikipedia codes have a ${lang} article`);
