// build_script.mjs: script/conversation.md + chapters/pronounce/overrides → script/script.yaml and script/summary.md.
//   node tools/build_script.mjs
// script.yaml is generated: edit the transcript's companions (chapters.yaml, pronounce.yaml, overrides.yaml), never it.
// Run tools/verbatim_check.mjs afterwards; it proves the result still matches the transcript word for word.
import { readFileSync, writeFileSync } from 'node:fs';
import YAML from 'yaml';
import { PATHS, PACE, readYaml, sha256, parseConversation, blocksToLines, SPOKEN_KINDS, compileRespellings, autoSpeech, words, pad, loadTypos, meant } from './script_lib.mjs';

const md = readFileSync(PATHS.conversation, 'utf8');
const conv = parseConversation(md);
const chapters = readYaml(PATHS.chapters);
const respellings = compileRespellings(readYaml(PATHS.pronounce));
const overrides = new Map((readYaml(PATHS.overrides) || []).map(o => [o.id, o]));
const lines = blocksToLines(conv);
const typos = loadTypos(lines);   // the voice says what Curt meant

// chapters: explicit ids first, then turn ranges
const chapterOf = new Map();
for (const c of chapters) for (const id of c.ids || []) chapterOf.set(id, c.n);
for (const l of lines) if (!chapterOf.has(l.id)) {
  const c = chapters.find(c => c.turns && l.turn >= c.turns[0] && l.turn <= c.turns[1]);
  if (!c) throw new Error(`no chapter for ${l.id}`);
  chapterOf.set(l.id, c.n);
}
for (const id of overrides.keys()) if (!lines.some(l => l.id === id)) throw new Error(`overrides.yaml: no line ${id}`);

const out = lines.map((l, i) => {
  const next = lines[i + 1];
  const o = { id: l.id, ch: chapterOf.get(l.id), speaker: l.speaker, kind: l.kind, text: l.text };
  const refs = [...l.text.matchAll(/\[([^\]]+)\]\((https?:\/\/[^)\s]+)\)/g)].map(m => ({ label: m[1], url: m[2] }));
  if (refs.length) o.refs = refs;
  o.spoken = SPOKEN_KINDS.has(l.kind);
  let est;
  if (o.spoken) {
    const ov = overrides.get(l.id);
    const auto = autoSpeech(meant(l.text, typos[l.id]), respellings);
    o.speech = ov ? ov.speech.trim().replace(/\s+/g, ' ') : auto.speech;
    o.speech_from = ov ? 'override' : 'auto';
    if (!ov && auto.used.length) o.respelled = auto.used;
    o.words = words(o.speech);
    est = o.words / PACE.wpm * 60;
  } else if (l.kind === 'table') est = PACE.tableBase + PACE.tableRow * (l.text.split('\n').length - 2);
  else if (l.kind === 'tool') est = PACE.tool;
  else if (l.kind === 'image') est = PACE.image;
  else est = 0;                                                   // sources ride along as QR codes
  const gap = !next || next.turn !== l.turn ? PACE.turnGap : l.speaker === 'curt' && next.speaker === 'claude' ? PACE.afterCurt : PACE.afterLine;
  o.est_s = +(est + (est ? gap : 0)).toFixed(1);
  return o;
});

const header = `# GENERATED by tools/build_script.mjs from ${PATHS.conversation}; do not edit.
# Edit script/chapters.yaml, script/pronounce.yaml or script/overrides.yaml and rebuild.
# Each line is one paragraph, list item, table, tool beat, image or sources block of the transcript, in order.
#   text:   the transcript's markdown, verbatim (what gets painted when words are shown)
#   speech: what the voice says (markdown stripped, Curt's typos read as he meant them, respellings applied, or a
#           reviewed override)
#   est_s:  a timing guess at ${PACE.wpm} wpm plus pauses and holds, until real TTS durations replace it
`;
const doc = { source: { file: PATHS.conversation, sha256: sha256(md), share: conv.source }, pace: PACE, lines: out };
writeFileSync(PATHS.script, header + YAML.stringify(doc, { lineWidth: 0 }));

// summary: runtime by chapter
const fmt = s => (s = Math.round(s), `${Math.floor(s / 60)}:${pad(s % 60)}`);
let tot = { lines: 0, words: 0, speech: 0, shown: 0, hold: 0 };
const rows = chapters.map(c => {
  const ls = out.filter(l => l.ch === c.n);
  const r = {
    lines: ls.length, words: ls.reduce((a, l) => a + (l.words || 0), 0),
    speech: ls.filter(l => l.spoken).reduce((a, l) => a + l.est_s, 0),
    shown: ls.filter(l => !l.spoken).reduce((a, l) => a + l.est_s, 0), hold: c.hold_s || 0,
  };
  for (const k in tot) tot[k] += r[k];
  const turns = c.turns ? `T${pad(c.turns[0])}–T${pad(c.turns[1])}` : c.ids.join(', ');
  return `| ${c.n} | ${c.title} | ${turns} | ${r.lines} | ${r.words.toLocaleString()} | ${fmt(r.speech)} | ${fmt(r.shown)} | ${fmt(r.hold)} | **${fmt(r.speech + r.shown + r.hold)}** |`;
});
const kinds = {}; for (const l of out) kinds[l.kind] = (kinds[l.kind] || 0) + 1;
writeFileSync(PATHS.summary, `# Script summary

Generated by \`tools/build_script.mjs\`. Timings are estimates: ${PACE.wpm} wpm, ${PACE.afterCurt} s after each of Curt's
prompts, ${PACE.afterLine} s between Claude's lines, ${PACE.turnGap} s between exchanges; painted tables held
${PACE.tableBase} s + ${PACE.tableRow} s per row; tool beats ${PACE.tool} s; attached images ${PACE.image} s; chapter holds from
\`chapters.yaml\`. Real TTS durations replace all of this in Phase 3.

| # | chapter | turns | lines | words | speech | shown only | holds | total |
|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}
| | **total** | | ${tot.lines} | ${tot.words.toLocaleString()} | ${fmt(tot.speech)} | ${fmt(tot.shown)} | ${fmt(tot.hold)} | **${fmt(tot.speech + tot.shown + tot.hold)}** |

Line kinds: ${Object.entries(kinds).map(([k, v]) => `${k} ${v}`).join(', ')}.
Speakers: Curt ${out.filter(l => l.speaker === 'curt' && l.spoken).reduce((a, l) => a + l.words, 0).toLocaleString()} words, Claude ${out.filter(l => l.speaker === 'claude' && l.spoken).reduce((a, l) => a + l.words, 0).toLocaleString()} words.
`);
console.log(`wrote ${PATHS.script} (${out.length} lines) and ${PATHS.summary}: ~${fmt(tot.speech + tot.shown + tot.hold)} total`);
