// qr_images.mjs: dresses every code whose style isn't painted in src/qr_styles.js with Still QR
// (github.com/curtcox/Still-QR-codes-to-me, checked out beside this repo, or wherever STILL_QR points).
//
//   node tools/qr_images.mjs          render every such code, framed and bare, into assets/qr/, and index them in
//                                     src/gen/qr_images.js (qr.js draws them in place of a painted code)
//
// Still QR renders at whole-pixel modules, checks each image decodes to its exact payload, and reports where the code
// sits in the image (its box, quiet zone included) and how far the frame reaches on each side. The film's own check
// (tools/qr_check.mjs) then reads every code again, through the engine, at its on-screen size.
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync, cpSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { loadRefs } from './script_lib.mjs';

const STILL = resolve(process.env.STILL_QR || '../Still-QR-codes-to-me'), MODULE_PX = 8;
if (!existsSync(join(STILL, 'src/cli.ts'))) { console.error(`Still QR isn't at ${STILL} (set STILL_QR)`); process.exit(1); }

// styles painted here win; everything else that has a style goes to Still QR
const src = readFileSync('src/qr_styles.js', 'utf8');
const native = new Set([...src.matchAll(/^  '?([a-z-]+)'?: \{/gm)].map(m => m[1]).concat('mad'));
const refs = loadRefs().filter(r => r.style && !native.has(r.style) && r.mode !== 'page');
const ecc = r => r.ecc || (r.mode === 'feature' ? 'H' : 'M');
const entries = refs.map(r => ({ id: r.id, style: r.style, text: r.qr_url || r.url, ecc: ecc(r), mode: r.mode, caption: r.caption || r.id, modulePx: MODULE_PX }));

const tmp = resolve('out/qr_images'); rmSync(tmp, { recursive: true, force: true }); mkdirSync(tmp, { recursive: true });
writeFileSync(join(tmp, 'manifest.json'), JSON.stringify(entries, null, 1));
const index = {}, styles = {};
for (const [variant, extra] of [['f', []], ['n', ['--frame', 'none']]]) {
  const out = join(tmp, variant);
  execFileSync('node', ['--import', 'tsx', 'src/cli.ts', '--batch', join(tmp, 'manifest.json'), '--out-dir', out, '--module-px', String(MODULE_PX), '--transparent', ...extra],
    { cwd: STILL, stdio: ['ignore', 'inherit', 'inherit'] });
  const dest = `assets/qr/${variant}`; rmSync(dest, { recursive: true, force: true }); mkdirSync(dest, { recursive: true });
  for (const e of entries) {
    const side = JSON.parse(readFileSync(join(out, e.id + '.json'), 'utf8')), b = side.codeBox, fr = side.frame || {};
    if (side.text !== e.text || side.ecc !== e.ecc) throw new Error(`${e.id}: Still QR encoded ${side.text} at ${side.ecc}`);
    cpSync(join(out, e.id + '.png'), `${dest}/${e.id}.png`);
    const key = `${e.style}|${e.ecc}|${variant}|${e.text}`, reach = (b.height / 2 + (fr.bottom || 0)) / b.height;
    index[key] = { file: `${dest}/${e.id}.png`, box: [b.x, b.y, b.width], img: [side.image.width, side.image.height], n: side.moduleCount, reach: +reach.toFixed(3) };
    if (variant === 'f') {
      const ext = .5 + Math.max(fr.top || 0, fr.right || 0, fr.bottom || 0, fr.left || 0) / b.width;
      styles[e.style] = { extent: +Math.max(styles[e.style]?.extent ?? .5, ext).toFixed(3) };
    }
  }
  const report = join(out, 'report.json');
  if (existsSync(report)) {
    const rep = JSON.parse(readFileSync(report, 'utf8')), rows = rep.entries || rep.results || [];
    const failed = rows.filter(r => r.passed === false || r.result === 'FAIL');
    console.log(`${variant === 'f' ? 'framed' : 'bare'}: ${rows.length - failed.length}/${rows.length} pass Still QR's checks${failed.length ? ': failing ' + failed.map(r => r.id).join(', ') : ''}`);
  }
}
const head = execFileSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: STILL }).toString().trim();
writeFileSync('src/gen/qr_images.js', `// GENERATED by tools/qr_images.mjs from Still QR ${head}; do not edit.\n` +
  `window.QR_IMAGES = ${JSON.stringify(index, null, 1)};\nwindow.QR_IMAGE_STYLES = ${JSON.stringify(styles, null, 1)};\n`);
console.log(`wrote ${Object.keys(index).length} images for ${refs.length} codes in ${Object.keys(styles).length} styles (Still QR ${head})`);
