// timeline.mjs: script/script.yaml (+ beats, + real voice durations once they exist) → the per-chapter timelines scenes
// run on, and the reference table.
//   node tools/timeline.mjs            writes src/gen/chNN.js for every chapter, src/gen/refs.js, script/timeline.md
// Until the voice is recorded, spoken lines last their word count at PACE.wpm; audio/durations.json ({ lineId: seconds })
// replaces those estimates line by line. script/beats.yaml adds deliberate holds: { lineId: { before, after } } seconds.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { PATHS, PACE, readYaml, pad, resolveAnchor } from './script_lib.mjs';

const script = readYaml(PATHS.script), chapters = readYaml(PATHS.chapters), refs = readYaml('script/refs.yaml');
const beats = existsSync('script/beats.yaml') ? readYaml('script/beats.yaml') || {} : {};
const voice = existsSync('audio/durations.json') ? JSON.parse(readFileSync('audio/durations.json', 'utf8')) : {};
const LEAD = 1.2, TAIL = 1.5;   // room for the transitions into and out of every chapter

// how long a line itself takes (its gap to the next line is separate)
function lengthOf(l) {
  if (voice[l.id] != null) return voice[l.id];
  if (l.spoken) return l.words / PACE.wpm * 60;
  if (l.kind === 'table') return PACE.tableBase + PACE.tableRow * (l.text.split('\n').length - 2);
  if (l.kind === 'tool') return PACE.tool;
  if (l.kind === 'image') return PACE.image;
  return 0;
}
function gapAfter(l, next) {
  if (!next || next.id.slice(0, 3) !== l.id.slice(0, 3)) return PACE.turnGap;
  return l.speaker === 'curt' && next.speaker === 'claude' ? PACE.afterCurt : PACE.afterLine;
}

const byId = new Map(script.lines.map(l => [l.id, l]));
for (const r of refs) r.line = resolveAnchor(r, script.lines, byId)?.id;
mkdirSync('src/gen', { recursive: true });
const summary = [];
for (const c of chapters) {
  const ls = script.lines.filter(l => l.ch === c.n);
  let t = LEAD;
  const out = ls.map((l, i) => {
    const b = beats[l.id] || {};
    t += b.before || 0;
    const t0 = t, len = lengthOf(l), t1 = t0 + len;
    t = t1 + gapAfter(l, ls[i + 1]) + (b.after || 0);
    return { id: l.id, speaker: l.speaker, kind: l.kind, spoken: l.spoken, t0: +t0.toFixed(3), t1: +t1.toFixed(3), end: +t.toFixed(3),
      text: l.text, ...(l.speech ? { speech: l.speech } : {}), refs: refs.filter(r => r.line === l.id).map(r => r.id), estimated: voice[l.id] == null };
  });
  const duration = +(t + (c.hold_s || 0) + TAIL).toFixed(3);
  const slug = `ch${pad(c.n)}_${c.slug}`;
  const ch = { n: c.n, slug: c.slug, title: c.title, scene: `${slug}.js`, lead: LEAD, duration, hold: c.hold_s || 0, lines: out };
  writeFileSync(`src/gen/ch${pad(c.n)}.js`, `// GENERATED by tools/timeline.mjs from script/script.yaml; do not edit.\nwindow.CHAPTER = ${JSON.stringify(ch, null, 1)};\n`);
  summary.push(`| ${c.n} | ${c.title} | ${out.length} | ${Math.floor(duration / 60)}:${pad(Math.round(duration % 60))} | ${!out.some(l => l.spoken) ? '—' : out.some(l => l.estimated && l.spoken) ? 'estimated' : 'voiced'} |`);
}
const table = Object.fromEntries(refs.map(({ line, ...r }) => [r.id, { ...r, line }]));
writeFileSync('src/gen/refs.js', `// GENERATED by tools/timeline.mjs from script/refs.yaml; do not edit.\nwindow.REFS = ${JSON.stringify(table, null, 1)};\n`);
writeFileSync('script/timeline.md', `# Timeline

Generated by \`tools/timeline.mjs\`. Each chapter opens with ${LEAD} s for its transition in and closes with ${TAIL} s out.
Spoken lines are estimated at ${PACE.wpm} wpm until audio/durations.json has real voice lengths.

| # | chapter | lines | length | timing |
|---|---|---|---|---|
${summary.join('\n')}
`);
console.log(`wrote src/gen/ch00..ch${pad(chapters.length - 1)}.js, src/gen/refs.js, script/timeline.md`);
