// verbatim_check.mjs: proves script/script.yaml says what the transcript says, and reports every place the voice
// differs from the page.
//   node tools/verbatim_check.mjs          exit 1 on any error; writes script/verbatim_report.md either way
// Checks:
//   1. conversation.md parses and re-renders byte for byte, and matches the hash script.yaml was built from
//   2. script.yaml's lines are the transcript's blocks, complete and in order, with identical text
//   3. every paragraph and list item is spoken; only tables, tool beats, images and sources blocks are silent
//   4. every spoken line's speech is exactly the automatic reading (markdown stripped + pronounce.yaml), or a
//      reviewed entry in overrides.yaml
import { readFileSync, writeFileSync } from 'node:fs';
import { PATHS, readYaml, sha256, parseConversation, renderConversation, blocksToLines, SPOKEN_KINDS, compileRespellings, autoSpeech } from './script_lib.mjs';

const errors = [], note = e => errors.push(e);
const md = readFileSync(PATHS.conversation, 'utf8');
const conv = parseConversation(md);
if (renderConversation(conv) !== md) note('conversation.md does not re-render byte for byte (parser drift)');
const script = readYaml(PATHS.script);
if (script.source.sha256 !== sha256(md)) note('script.yaml was built from a different conversation.md: rebuild it');

const want = blocksToLines(conv), got = script.lines;
if (want.length !== got.length) note(`line count: transcript has ${want.length}, script.yaml has ${got.length}`);
for (let i = 0; i < Math.min(want.length, got.length); i++) {
  const w = want[i], g = got[i];
  if (w.id !== g.id) { note(`line ${i}: expected ${w.id}, found ${g.id}`); break; }
  if (w.text !== g.text) note(`${g.id}: text differs from the transcript`);
  if (w.kind !== g.kind || w.speaker !== g.speaker) note(`${g.id}: kind/speaker changed`);
  if (SPOKEN_KINDS.has(w.kind) !== !!g.spoken) note(`${g.id}: ${w.kind} must ${SPOKEN_KINDS.has(w.kind) ? '' : 'not '}be spoken`);
}

const respellings = compileRespellings(readYaml(PATHS.pronounce));
const overrides = new Map((readYaml(PATHS.overrides) || []).map(o => [o.id, o]));
const used = new Map(), ovRows = [];
for (const g of got.filter(l => l.spoken)) {
  const ov = overrides.get(g.id);
  const expect = ov ? ov.speech.trim().replace(/\s+/g, ' ') : autoSpeech(g.text, respellings).speech;
  if (g.speech !== expect) note(`${g.id}: speech isn't the ${ov ? 'override' : 'automatic reading'}`);
  if (ov) ovRows.push({ g, ov });
  else for (const m of autoSpeech(g.text, respellings).used) used.set(m, [...(used.get(m) || []), g.id]);
}
for (const id of overrides.keys()) if (!got.some(l => l.id === id)) note(`overrides.yaml: no line ${id}`);

// ---- report ---------------------------------------------------------------------------------------------------
const silent = {}; for (const g of got.filter(l => !l.spoken)) (silent[g.kind] ||= []).push(g.id);
const byMatch = new Map(readYaml(PATHS.pronounce).map(r => [r.match, r]));
const q = s => '`' + s.replace(/`/g, "'") + '`';
const report = `# Verbatim report

Generated by \`tools/verbatim_check.mjs\`. **${errors.length ? `${errors.length} error(s)` : 'No errors'}.**

- Transcript: \`${PATHS.conversation}\` (sha256 \`${sha256(md).slice(0, 16)}…\`), ${conv.turns.length} turns, ${got.length} script lines.
- Every paragraph and list item is spoken. Every spoken line is the transcript's own words with markdown removed,
  except where one of the two lists below says otherwise.
${errors.length ? '\n## Errors\n\n' + errors.map(e => '- ' + e).join('\n') + '\n' : ''}
## 1. Overrides (${ovRows.length}): hand-written speech, for review

${ovRows.map(({ g, ov }) => `### ${g.id} (${g.speaker})\n\n*Why:* ${ov.reason.trim()}\n\n**Transcript:**\n\n${g.text.split('\n').map(l => '> ' + l).join('\n')}\n\n**Voice:**\n\n> ${g.speech}\n`).join('\n')}
## 2. Respellings (${used.size} in use): the voice says the right-hand side where the page shows the left

| written | spoken | lines | check by ear |
|---|---|---|---|
${[...used].map(([m, ids]) => `| ${q(m)} | ${q(byMatch.get(m).say)} | ${ids.join(', ')} | ${byMatch.get(m).verify ? 'yes' : ''} |`).join('\n')}

Unused entries in \`pronounce.yaml\`: ${[...byMatch.keys()].filter(m => !used.has(m)).map(q).join(', ') || 'none'}.

## 3. Silent lines: shown, not read

${Object.entries(silent).map(([k, ids]) => `- **${k}** (${ids.length}): ${ids.join(', ')}`).join('\n')}

Tables are painted with every number exact; tool beats become short visual beats; attached images are repainted;
sources blocks and inline citation chips become QR codes.
`;
writeFileSync(PATHS.report, report);
if (errors.length) { console.error(errors.join('\n')); console.error(`${errors.length} error(s); see ${PATHS.report}`); process.exit(1); }
console.log(`verbatim: ok (${got.filter(l => l.spoken).length} spoken lines, ${ovRows.length} overrides, ${used.size} respellings); wrote ${PATHS.report}`);
